version: '3.6'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: project-go
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
      

volumes:
  db-data: {}
  postgres-data: {}