### CREATE USER
POST http://localhost:3001/api/users/ HTTP/1.1
Content-Type: application/json

{
    "first_name": "quoi",
    "last_name": "feur",
    "email": "quoi@feur.fr",
    "password": "test1234"
}

### LOGIN USER
POST http://localhost:3001/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "quoi@feur.fr",
    "password": "test1234"
}

### CURRENT USER
GET http://localhost:3001/api/users/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNzQzNzU4MTEzfQ.dtjeeBAbPnhT4IZOSCGSHbe3Wnr03AQ8Jsuy6OY7NkE

###

### GET ALL USER
GET http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNzQzNzU4MTEzfQ.dtjeeBAbPnhT4IZOSCGSHbe3Wnr03AQ8Jsuy6OY7NkE

###