### CREATE USER
POST http://localhost:5000/api/users/ HTTP/1.1
Content-Type: application/json

{
    "first_name": "admin",
    "last_name": "admin",
    "email": "admin@admin.fr",
    "password": "test1234"
}

### LOGIN USER
POST http://localhost:5000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@admin.fr",
    "password": "test1234"
}

### VALIDATE ACCOUNT USER
GET http://localhost:5000/api/users/validate/dfd HTTP/1.1
Content-Type: application/json

###

### CURRENT USER
GET http://localhost:5000/api/users/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImV4cCI6MTc0Nzk5MTgxMn0.BiCoBclwBu68FEIR7ihVUe1GvhXN3xS8Tn_3vZ3T794

###

### GET ALL USER
GET http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImV4cCI6MTc1MTk5NzUyNH0.ZigCeukUPkioAL-Fln9sUQ6wtzTBrjG-MyUnKRrNdug

###