branch-defaults:
  default:
    environment: prod-env
    group_suffix: null
global:
  application_name: airfleet
  branch: null
  default_ec2_keyname: airfleet-eb
  default_platform: Go 1
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
