basePath: /api
definitions:
  handlers.Response:
    properties:
      message:
        type: string
    type: object
  inputs.InputCreatePilot:
    type: object
  inputs.InputCreateUser:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  inputs.InputCreateVehicle:
    properties:
      matriculation:
        type: string
      model_name:
        type: string
      seat:
        type: integer
      type:
        type: string
      user_id:
        type: integer
    required:
    - matriculation
    - model_name
    - seat
    - type
    - user_id
    type: object
  inputs.InputLoginUser:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  inputs.InputUpdateVehicle:
    properties:
      matriculation:
        type: string
      model_name:
        type: string
      seat:
        type: integer
      type:
        type: string
      user_id:
        type: integer
    type: object
  responses.ResponseListUser:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      is_verified:
        type: boolean
      last_name:
        type: string
      updated_at:
        type: string
    type: object
  responses.ResponseLogin:
    properties:
      token:
        type: string
    type: object
  responses.ResponseUser:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      role:
        type: string
      updated_at:
        type: string
      vehicles:
        items:
          $ref: '#/definitions/responses.ResponseVehicle'
        type: array
    type: object
  responses.ResponseVehicle:
    properties:
      created_at:
        type: string
      id:
        type: integer
      is_verified:
        type: boolean
      matriculation:
        type: string
      model_name:
        type: string
      seat:
        type: integer
      type:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
  description: this is the go project.
  title: Backend AirFleet
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: get all user for admins
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.ResponseListUser'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.Response'
      security:
      - BearerAuth: []
      summary: Get all users
      tags:
      - user
    post:
      consumes:
      - application/json
      description: register for a normal client
      parameters:
      - description: Message body
        in: body
        name: userInput
        required: true
        schema:
          $ref: '#/definitions/inputs.InputCreateUser'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.ResponseUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Register user
      tags:
      - user
  /users/login:
    post:
      consumes:
      - application/json
      description: login a client
      parameters:
      - description: Message body
        in: body
        name: userInput
        required: true
        schema:
          $ref: '#/definitions/inputs.InputLoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ResponseLogin'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Login
      tags:
      - user
  /users/me:
    get:
      consumes:
      - application/json
      description: get current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ResponseUser'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.Response'
      security:
      - BearerAuth: []
      summary: Current user
      tags:
      - user
  /users/pilot:
    post:
      consumes:
      - multipart/form-data
      description: register for a pilot
      parameters:
      - description: Message body
        in: body
        name: userInput
        required: true
        schema:
          $ref: '#/definitions/inputs.InputCreatePilot'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.ResponseUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Register pilot
      tags:
      - user
  /vehicles:
    get:
      consumes:
      - application/json
      description: get all vehicles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.ResponseVehicle'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.Response'
      security:
      - BearerAuth: []
      summary: Get all vehicles
      tags:
      - vehicle
    post:
      consumes:
      - application/json
      description: create a new vehicle for a pilot
      parameters:
      - description: Message body
        in: body
        name: vehicleInput
        required: true
        schema:
          $ref: '#/definitions/inputs.InputCreateVehicle'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.ResponseVehicle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Create vehicle
      tags:
      - vehicle
  /vehicles/{id}:
    delete:
      consumes:
      - application/json
      description: delete vehicle by id
      parameters:
      - description: Vehicle ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: delete vehicle by id
      tags:
      - vehicle
    get:
      consumes:
      - application/json
      description: get vehicle by id
      parameters:
      - description: Vehicle ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ResponseVehicle'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: get vehicle by id
      tags:
      - vehicle
    patch:
      consumes:
      - application/json
      description: update vehicle by id
      parameters:
      - description: Vehicle ID
        in: path
        name: id
        required: true
        type: integer
      - description: Message body
        in: body
        name: vehicleInput
        required: true
        schema:
          $ref: '#/definitions/inputs.InputUpdateVehicle'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ResponseVehicle'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: update vehicle by id
      tags:
      - vehicle
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
